name: Build Kivy Android APK

on: 
  push:
    branches:
      - main  # Runs when code is pushed to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: false  # ✅ Prevents Git submodule issues
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Buildozer and Dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3 python3-pip \
          python3-venv python3-dev ffmpeg libsdl2-dev libsdl2-image-dev \
          libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev \
          libavcodec-dev libavformat-dev libglu1-mesa
        pip install --upgrade pip
        pip install buildozer cython python-for-android
        buildozer -v android update  # ✅ Ensure required files are downloaded

    - name: Remove Old Buildozer Cache & Fix Submodules
      run: |
        rm -rf .buildozer/  # ✅ Remove previous builds to avoid issues
        rm -rf .gitmodules  # ✅ Prevent Git submodule errors

    - name: Initialize Buildozer (Only if Missing)
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        else
          echo "buildozer.spec already exists. Skipping init."
        fi

    - name: Accept Android SDK Licenses and Install Build-Tools
      run: |
        export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
        export ANDROID_HOME=$ANDROID_SDK_ROOT
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        mkdir -p $ANDROID_SDK_ROOT/licenses
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $ANDROID_SDK_ROOT/licenses/android-sdk-license
        echo "84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_SDK_ROOT/licenses/android-sdk-preview-license
        yes | sdkmanager --licenses || true
        yes | sdkmanager "build-tools;36.0.0-rc5" || true  # ✅ Force install the missing build-tools version

    - name: Fix Missing Buildozer Files
      run: |
        buildozer -v android clean
        buildozer -v android update
        buildozer -v android sdk install  # ✅ Force install missing Android SDK

    - name: Build APK
      run: buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Android-APK
        path: bin/*.apk
