name: Build Kivy Android APK

on: 
  push:
    branches:
      - main  # Runs when code is pushed to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: false  # ✅ Disable submodules since Buildozer handles them
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3 python3-pip \
          python3-venv python3-dev ffmpeg libsdl2-dev libsdl2-image-dev \
          libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev \
          libavcodec-dev libavformat-dev libglu1-mesa
        pip install --upgrade pip
        pip install buildozer cython

    - name: Remove Old Buildozer Cache
      run: |
        rm -rf .buildozer/  # ✅ Remove previous builds to avoid submodule issues

    - name: Initialize Buildozer (Only if Missing)
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        else
          echo "buildozer.spec already exists. Skipping init."
        fi

    - name: Force Buildozer to Download Dependencies
      run: buildozer -v android clean

    - name: Build APK
      run: buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Android-APK
        path: bin/*.apk
